In [1]:
# Artificial Neural Network

# Installing Theano
# pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
# pip install tensorflow

# Installing Keras
# pip install --upgrade keras

# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')

In [3]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [5]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [6]:
X[0:5]

array([[619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1]],
      dtype=object)

In [7]:
X.shape

(10000, 10)

In [8]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [9]:
X.shape

(10000, 10)

In [11]:
onehotencoder = OneHotEncoder(drop="first")
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

In [12]:
X.shape

(10000, 16924)

In [13]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [14]:
print(X_train.shape,y_train.shape)

(8000, 16924) (8000,)


In [15]:
X_train[0:5]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [16]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
print(X_train.shape,X_test.shape)

(8000, 16924) (2000, 16924)


#Using Only Input and Output Layers

In [18]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
#classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 10))

# Adding the second hidden layer
#classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 2s 2ms/step - loss: 13.1899 - accuracy: 0.4746
Epoch 2/100
800/800 [==============================] - 2s 2ms/step - loss: 9.8257 - accuracy: 0.5882
Epoch 3/100
800/800 [==============================] - 1s 2ms/step - loss: 7.4217 - accuracy: 0.7262
Epoch 4/100
800/800 [==============================] - 2s 2ms/step - loss: 5.9281 - accuracy: 0.8166
Epoch 5/100
800/800 [==============================] - 2s 2ms/step - loss: 5.2786 - accuracy: 0.8636
Epoch 6/100
800/800 [==============================] - 2s 2ms/step - loss: 4.8299 - accuracy: 0.8802
Epoch 7/100
800/800 [==============================] - 2s 2ms/step - loss: 4.4177 - accuracy: 0.8845
Epoch 8/100
800/800 [==============================] - 2s 2ms/step - loss: 4.0214 - accuracy: 0.8873
Epoch 9/100
800/800 [==============================] - 2s 2ms/step - loss: 3.6260 - accuracy: 0.8889
Epoch 10/100
800/800 [==============================] - 2s 2ms/step - loss: 3.2402 - accur

In [19]:
import warnings
warnings.filterwarnings("ignore")

# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix \n")
print(cm)
print("\n")
# classification report for precision, recall f1-score and accuracy
from sklearn.metrics import classification_report
matrix = classification_report(y_test,y_pred)
print('Classification report : \n',matrix)

Confusion Matrix 

[[1592    3]
 [ 404    1]]


Classification report : 
               precision    recall  f1-score   support

           0       0.80      1.00      0.89      1595
           1       0.25      0.00      0.00       405

    accuracy                           0.80      2000
   macro avg       0.52      0.50      0.45      2000
weighted avg       0.69      0.80      0.71      2000



#Using Input , One Hidden Layer and Output Layers

In [20]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 16924))

# Adding the second hidden layer
#classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 3s 4ms/step - loss: 0.5435 - accuracy: 0.7876
Epoch 2/100
800/800 [==============================] - 3s 4ms/step - loss: 0.4549 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 3s 3ms/step - loss: 0.3787 - accuracy: 0.7960
Epoch 4/100
800/800 [==============================] - 3s 3ms/step - loss: 0.2925 - accuracy: 0.7960
Epoch 5/100
800/800 [==============================] - 3s 3ms/step - loss: 0.2356 - accuracy: 0.8336
Epoch 6/100
800/800 [==============================] - 3s 4ms/step - loss: 0.2133 - accuracy: 0.8884
Epoch 7/100
800/800 [==============================] - 3s 3ms/step - loss: 0.2042 - accuracy: 0.8929
Epoch 8/100
800/800 [==============================] - 3s 3ms/step - loss: 0.2010 - accuracy: 0.8938
Epoch 9/100
800/800 [==============================] - 3s 3ms/step - loss: 0.2001 - accuracy: 0.8938
Epoch 10/100
800/800 [==============================] - 3s 3ms/step - loss: 0.1990 - accura

In [21]:
# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix \n")
print(cm)
print("\n")
# classification report for precision, recall f1-score and accuracy
from sklearn.metrics import classification_report
matrix = classification_report(y_test,y_pred)
print('Classification report : \n',matrix)

Confusion Matrix 

[[1595    0]
 [ 405    0]]


Classification report : 
               precision    recall  f1-score   support

           0       0.80      1.00      0.89      1595
           1       0.00      0.00      0.00       405

    accuracy                           0.80      2000
   macro avg       0.40      0.50      0.44      2000
weighted avg       0.64      0.80      0.71      2000



#Using Input , Two Hidden Layers and Output Layers

In [23]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 16924))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 5s 5ms/step - loss: 0.5360 - accuracy: 0.7944
Epoch 2/100
800/800 [==============================] - 5s 6ms/step - loss: 0.4709 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 3s 4ms/step - loss: 0.4204 - accuracy: 0.7960
Epoch 4/100
800/800 [==============================] - 3s 4ms/step - loss: 0.3496 - accuracy: 0.7960
Epoch 5/100
800/800 [==============================] - 3s 4ms/step - loss: 0.2866 - accuracy: 0.8130
Epoch 6/100
800/800 [==============================] - 3s 4ms/step - loss: 0.2568 - accuracy: 0.8400
Epoch 7/100
800/800 [==============================] - 3s 4ms/step - loss: 0.2419 - accuracy: 0.8531
Epoch 8/100
800/800 [==============================] - 3s 4ms/step - loss: 0.2357 - accuracy: 0.8572
Epoch 9/100
800/800 [==============================] - 3s 4ms/step - loss: 0.2339 - accuracy: 0.8590
Epoch 10/100
800/800 [==============================] - 3s 4ms/step - loss: 0.2332 - accura

In [24]:
# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix \n")
print(cm)
print("\n")
# classification report for precision, recall f1-score and accuracy
from sklearn.metrics import classification_report
matrix = classification_report(y_test,y_pred)
print('Classification report : \n',matrix)

Confusion Matrix 

[[1595    0]
 [ 405    0]]


Classification report : 
               precision    recall  f1-score   support

           0       0.80      1.00      0.89      1595
           1       0.00      0.00      0.00       405

    accuracy                           0.80      2000
   macro avg       0.40      0.50      0.44      2000
weighted avg       0.64      0.80      0.71      2000

