In [1]:
# Artificial Neural Network

# Installing Theano
# pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
# pip install tensorflow

# Installing Keras
# pip install --upgrade keras

# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')

In [3]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [5]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [6]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [7]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [8]:
print(X_train.shape,y_train.shape)

(8000, 10) (8000,)


In [9]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Without Regularization

In [10]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 10))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 1s 944us/step - loss: 0.4884 - accuracy: 0.7960
Epoch 2/100
800/800 [==============================] - 1s 937us/step - loss: 0.4327 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 1s 921us/step - loss: 0.4258 - accuracy: 0.7968
Epoch 4/100
800/800 [==============================] - 1s 934us/step - loss: 0.4215 - accuracy: 0.8227
Epoch 5/100
800/800 [==============================] - 1s 945us/step - loss: 0.4186 - accuracy: 0.8266
Epoch 6/100
800/800 [==============================] - 1s 915us/step - loss: 0.4174 - accuracy: 0.8315
Epoch 7/100
800/800 [==============================] - 1s 907us/step - loss: 0.4153 - accuracy: 0.8319
Epoch 8/100
800/800 [==============================] - 1s 919us/step - loss: 0.4139 - accuracy: 0.8328
Epoch 9/100
800/800 [==============================] - 1s 916us/step - loss: 0.4129 - accuracy: 0.8328
Epoch 10/100
800/800 [==============================] - 1s 937us/step - l

In [11]:
import warnings
warnings.filterwarnings("ignore")

# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix \n")
print(cm)
print("\n")
# classification report for precision, recall f1-score and accuracy
from sklearn.metrics import classification_report
matrix = classification_report(y_test,y_pred)
print('Classification report : \n',matrix)

Confusion Matrix 

[[1535   60]
 [ 249  156]]


Classification report : 
               precision    recall  f1-score   support

           0       0.86      0.96      0.91      1595
           1       0.72      0.39      0.50       405

    accuracy                           0.85      2000
   macro avg       0.79      0.67      0.71      2000
weighted avg       0.83      0.85      0.83      2000



#With L1 Regularization

In [16]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras import regularizers


# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform',kernel_regularizer=regularizers.l1(1e-5) ,activation = 'relu', input_dim = 10))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform',kernel_regularizer=regularizers.l1(1e-5) ,activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform',kernel_regularizer=regularizers.l1(1e-5) ,activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 1s 990us/step - loss: 0.4854 - accuracy: 0.7954
Epoch 2/100
800/800 [==============================] - 1s 967us/step - loss: 0.4331 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 1s 966us/step - loss: 0.4281 - accuracy: 0.7960
Epoch 4/100
800/800 [==============================] - 1s 988us/step - loss: 0.4242 - accuracy: 0.8146
Epoch 5/100
800/800 [==============================] - 1s 940us/step - loss: 0.4212 - accuracy: 0.8256
Epoch 6/100
800/800 [==============================] - 1s 981us/step - loss: 0.4194 - accuracy: 0.8273
Epoch 7/100
800/800 [==============================] - 1s 930us/step - loss: 0.4175 - accuracy: 0.8301
Epoch 8/100
800/800 [==============================] - 1s 966us/step - loss: 0.4160 - accuracy: 0.8324
Epoch 9/100
800/800 [==============================] - 1s 964us/step - loss: 0.4147 - accuracy: 0.8322
Epoch 10/100
800/800 [==============================] - 1s 883us/step - l

In [17]:
import warnings
warnings.filterwarnings("ignore")

# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix \n")
print(cm)
print("\n")
# classification report for precision, recall f1-score and accuracy
from sklearn.metrics import classification_report
matrix = classification_report(y_test,y_pred)
print('Classification report : \n',matrix)

Confusion Matrix 

[[1547   48]
 [ 269  136]]


Classification report : 
               precision    recall  f1-score   support

           0       0.85      0.97      0.91      1595
           1       0.74      0.34      0.46       405

    accuracy                           0.84      2000
   macro avg       0.80      0.65      0.68      2000
weighted avg       0.83      0.84      0.82      2000



#With L2 Regularization

In [18]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras import regularizers


# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform',kernel_regularizer=regularizers.l2(1e-4) ,activation = 'relu', input_dim = 10))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform',kernel_regularizer=regularizers.l2(1e-4) ,activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform',kernel_regularizer=regularizers.l2(1e-4) ,activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 1s 992us/step - loss: 0.4941 - accuracy: 0.7958
Epoch 2/100
800/800 [==============================] - 1s 995us/step - loss: 0.4356 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 1s 970us/step - loss: 0.4324 - accuracy: 0.7960
Epoch 4/100
800/800 [==============================] - 1s 948us/step - loss: 0.4294 - accuracy: 0.7960
Epoch 5/100
800/800 [==============================] - 1s 957us/step - loss: 0.4256 - accuracy: 0.8114
Epoch 6/100
800/800 [==============================] - 1s 982us/step - loss: 0.4226 - accuracy: 0.8217
Epoch 7/100
800/800 [==============================] - 1s 946us/step - loss: 0.4202 - accuracy: 0.8259
Epoch 8/100
800/800 [==============================] - 1s 982us/step - loss: 0.4183 - accuracy: 0.8285
Epoch 9/100
800/800 [==============================] - 1s 955us/step - loss: 0.4167 - accuracy: 0.8313
Epoch 10/100
800/800 [==============================] - 1s 960us/step - l

In [19]:
import warnings
warnings.filterwarnings("ignore")

# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix \n")
print(cm)
print("\n")
# classification report for precision, recall f1-score and accuracy
from sklearn.metrics import classification_report
matrix = classification_report(y_test,y_pred)
print('Classification report : \n',matrix)

Confusion Matrix 

[[1546   49]
 [ 264  141]]


Classification report : 
               precision    recall  f1-score   support

           0       0.85      0.97      0.91      1595
           1       0.74      0.35      0.47       405

    accuracy                           0.84      2000
   macro avg       0.80      0.66      0.69      2000
weighted avg       0.83      0.84      0.82      2000

