In [99]:
# Artificial Neural Network

# Installing Theano
# pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
# pip install tensorflow

# Installing Keras
# pip install --upgrade keras

# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [100]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')


In [101]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [102]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [103]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [104]:
X[0:5]

array([[619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1]],
      dtype=object)

In [105]:
X.shape

(10000, 10)

In [106]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [107]:
X.shape

(10000, 10)

In [108]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [109]:
print(X_train.shape,y_train.shape)

(8000, 10) (8000,)


In [110]:
X_train[0:5]

array([[667, 2, 0, 34, 5, 0.0, 2, 1, 0, 163830.64],
       [427, 1, 1, 42, 1, 75681.52, 1, 1, 1, 57098.0],
       [535, 0, 0, 29, 2, 112367.34, 1, 1, 0, 185630.76],
       [654, 2, 1, 40, 5, 105683.63, 1, 1, 0, 173617.09],
       [850, 2, 0, 57, 8, 126776.3, 2, 1, 1, 132298.49]], dtype=object)

In [112]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [113]:
print(X_train.shape,X_test.shape)

(8000, 10) (2000, 10)


In [114]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 10))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 3s 3ms/step - loss: 0.4909 - accuracy: 0.7956
Epoch 2/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4303 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 3s 3ms/step - loss: 0.4236 - accuracy: 0.8142
Epoch 4/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4181 - accuracy: 0.8311
Epoch 5/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4143 - accuracy: 0.8329
Epoch 6/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4113 - accuracy: 0.8332
Epoch 7/100
800/800 [==============================] - 3s 3ms/step - loss: 0.4090 - accuracy: 0.8340
Epoch 8/100
800/800 [==============================] - 3s 3ms/step - loss: 0.4075 - accuracy: 0.8324
Epoch 9/100
800/800 [==============================] - 3s 3ms/step - loss: 0.4064 - accuracy: 0.8338
Epoch 10/100
800/800 [==============================] - 3s 3ms/step - loss: 0.4051 - accura

In [115]:
import warnings
warnings.filterwarnings("ignore")

# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix \n")
print(cm)
print("\n")
# classification report for precision, recall f1-score and accuracy
from sklearn.metrics import classification_report
matrix = classification_report(y_test,y_pred)
print('Classification report : \n',matrix)

Confusion Matrix 

[[1543   52]
 [ 217  188]]


Classification report : 
               precision    recall  f1-score   support

           0       0.88      0.97      0.92      1595
           1       0.78      0.46      0.58       405

    accuracy                           0.87      2000
   macro avg       0.83      0.72      0.75      2000
weighted avg       0.86      0.87      0.85      2000

